import Link from "next/link";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { AI_DISCLOSURE_TEXT, IDENTITY_DISCLAIMER_TEXT } from "@/lib/personas";

// Ethics page — §3 deliverable: "an ethics document recording every
// trust/delegation design decision"
export default function EthicsPage() {
  const decisions = [
    {
      title: "Speech rights first — eligibility by self-declaration",
      body: "The platform is open to any 18–25 year-old leader who cannot speak or record naturally due to a health condition: vocal cord injury, severe anxiety, ALS, stroke recovery, chronic fatigue syndrome, and more. We do not require medical proof — medical proof is itself a privilege, and it gates out exactly the people who most need to be heard. Eligibility is confirmed by a short public statement; the judgment of trust is delegated to the community and donors.",
      ref: "§2.1",
    },
    {
      title: "No identity verification — the judgment is yours",
      body: `The platform asks only for an email and an age self-declaration. No KYC, no phone verification, no OAuth. "${IDENTITY_DISCLAIMER_TEXT}" is displayed site-wide, permanently. We chose to make fraud risk visible rather than to filter out real people with screening walls.`,
      ref: "§2.3",
    },
    {
      title: "AI disclosure is non-negotiable",
      body: `Every voice is generated by ElevenLabs with the native AI-disclosure flag embedded in the request, and every page carries a visible label: "${AI_DISCLOSURE_TEXT}". We never pretend to be a human voice — disclosure is respect for the listener.`,
      ref: "§2.4",
    },
    {
      title: "Public health statements: a feature, not a breach",
      body: "The health statement a creator submits is displayed publicly on the project page. That is not a privacy violation — it is the foundation of community trust. Donors see a real person with a name and a situation, not an anonymous ask.",
      ref: "§2.4",
    },
    {
      title: "The platform never touches money",
      body: "Donations are purely peer-to-peer: SOL moves from the donor's wallet directly to the creator's wallet, signed by the donor's own Phantom. The platform never holds, routes, or custodies funds. Donors without a wallet can use a 'pledge' — stored only in their own browser, clearly labeled as simulated.",
      ref: "§2.2",
    },
    {
      title: "A public ledger of trust",
      body: "Every content anchor (the creator's Memo transaction carrying a SHA-256 content hash) and every donation signature is public and independently verifiable on the Solana Devnet explorer. Trust doesn't rest on the platform's promises — it rests on publicly auditable on-chain facts. No custom Solana programs are deployed, keeping the attack surface and audit burden at zero.",
      ref: "§2.3",
    },
  ];

  return (
    <div className="mx-auto w-full max-w-3xl px-6 py-10">
      <h1 className="text-3xl font-bold">Our trust design</h1>
      <p className="mt-3 text-muted-foreground">
        Every ethical decision behind SpeakForward is the product itself, not a
        compliance burden. These decisions were finalized before development
        began — they are not traded away under deadline pressure.
      </p>
      <div className="mt-8 space-y-4">
        {decisions.map((d) => (
          <Card key={d.title}>
            <CardHeader>
              <div className="flex flex-wrap items-center gap-2">
                <CardTitle className="text-lg">{d.title}</CardTitle>
                <span className="rounded-full border px-2 py-0.5 text-xs text-muted-foreground">
                  Spec {d.ref}
                </span>
              </div>
              <CardDescription />
            </CardHeader>
            <CardContent>
              <p className="text-sm leading-6 text-muted-foreground">{d.body}</p>
            </CardContent>
          </Card>
        ))}
      </div>
      <div className="mt-8 text-center">
        <Button variant="outline" render={<Link href="/" />}>
          ← Back home
        </Button>
      </div>
    </div>
  );
}
